import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "../styles/Home.module.css";
import Topic from "@/components/main-movie/Topic";
import Profile from "@/components/main-profile/Profile";
import Copy from "@/components/main-copy/Copy";
import Header from "@/components/header/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Copy />
      <Topic />
      <Profile />

      <div id="root"></div>
    </>
  );
}
